config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "flats#index"
  
  get "/show/:id", to: "flats#show", as: "flat"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  before_action :set_flats
  
  def index
  end

  def show
    flat_id = params[:id].to_i

    @flat = @flats.find { |flat| flat["id"] == flat_id }
  end

  private

  def set_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(URI.open(url).read) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Here are all of our flats:</h1>

<ul>
  <% @flats.each do |flat| %>
    <li>
      <%= link_to flat_path(flat["id"]) do %>
        <h2><%= flat["name"] %></h2>
        <p><%= flat["price"] %> <%= flat["priceCurrency"] %></p>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/flats/show.html.erb
<%= link_to "< Go back to our Flats", root_path %>

<h1>This Flat:</h1>

<h2><%= @flat["name"] %></h2>
<p><%= @flat["price"] %> <%= @flat["priceCurrency"] %></p>

<%= image_tag @flat["imageUrl"], width: "800px" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbSimple</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>